name: chaserobinengineering
favicon: null
layout_spectrum: 0.5148593769408762
typography_spectrum: 0.70528564741835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2767465172801167
  lightness: 0.6972148970235139
  saturation: 0.6748920299578458
  rhythmicContrast: 0.2959094459656626
purpose: []
